services:
  bookapp:
    depends_on:
      - mysql
    build:
      context: .
    ports:
      - 8080:8080

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # 
      - mysql-data1:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql-data1:
